"""include phone field for users

Revision ID: 626373aed9b3
Revises: d706f9c9343c
Create Date: 2019-03-28 02:00:07.076608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626373aed9b3'
down_revision = 'd706f9c9343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
